FROM node:13-buster-slim as builder

WORKDIR /app
ADD package.json yarn.lock ./
RUN yarn --frozen-lockfile --non-interactive

# Get a clean image with gatsby-cli and the pre-built node modules
FROM node:13-buster-slim
RUN yarn global add gatsby-cli && gatsby telemetry --disable && mkdir /save
COPY --from=builder /app/node_modules /save/node_modules