// Viz settings
export let defaultState = {
    M0: 100,
    M1: 100,
    SD: 15,
    xAxis: "mean",
    n: 5,
    SE: 15 / Math.sqrt(5),
    data: [],
    numDraws: 0,
    add: 0,
    pvals: [],
    sliding: false,
    highlight: false,
    pHacked: 0,
    cohend: 0,
    shift: 0,
    clear: false,
    phacked: false,
    sliderMax: 2,
    sliderStep: 0.01,
    immediate: false,
  };